# StockAnalyzer Pro Configuration

# Methodology Weights
methodology:
  weights:
    fundamental: 0.40    # P/E, EV/EBITDA, PEG, FCF Yield
    quality: 0.25        # ROE, ROIC, Debt ratios
    growth: 0.20         # Revenue/EPS growth
    sentiment: 0.15      # News + social sentiment

# Data Sources
data_sources:
  yahoo_finance:
    enabled: true
    rate_limit_per_hour: 2000
    timeout: 30
  
  reddit:
    enabled: true
    rate_limit_per_minute: 60
    subreddits:
      - "investing"
      - "stocks" 
      - "SecurityAnalysis"
      - "StockMarket"
      - "ValueInvesting"
      - "pennystocks"
      - "wallstreetbets"
    timeout: 30

# Database
database:
  type: "sqlite"
  path: "data/stock_data.db"
  
# Stock Universe (POC)
stocks:
  # Sample S&P 500 stocks for POC
  sample_symbols:
    - "AAPL"   # Apple
    - "MSFT"   # Microsoft  
    - "GOOGL"  # Alphabet
    - "AMZN"   # Amazon
    - "NVDA"   # NVIDIA
    - "TSLA"   # Tesla
    - "META"   # Meta
    - "BRK-B"  # Berkshire Hathaway
    - "UNH"    # UnitedHealth
    - "JNJ"    # Johnson & Johnson
    - "JPM"    # JPMorgan Chase
    - "V"      # Visa
    - "PG"     # Procter & Gamble
    - "HD"     # Home Depot
    - "MA"     # Mastercard
    - "AVGO"   # Broadcom
    - "PFE"    # Pfizer
    - "BAC"    # Bank of America
    - "ABBV"   # AbbVie
    - "KO"     # Coca-Cola
    - "TMO"    # Thermo Fisher
    - "COST"   # Costco
    - "MRK"    # Merck
    - "PEP"    # PepsiCo
    - "WMT"    # Walmart
    - "ADBE"   # Adobe
    - "DIS"    # Disney
    - "ABT"    # Abbott
    - "CRM"    # Salesforce
    - "VZ"     # Verizon

# Dashboard Settings  
dashboard:
  title: "StockAnalyzer Pro - POC"
  page_icon: "📊"
  layout: "wide"
  sidebar_expanded: true
  
# API Configuration Templates
api_templates:
  yahoo_finance:
    description: "Yahoo Finance API (yfinance library)"
    required_fields: []  # No credentials required for basic access
    optional_fields: []
    test_endpoint: "stock_info"
    rate_limits:
      requests_per_hour: 2000
  
  reddit:
    description: "Reddit API for sentiment analysis"
    required_fields: ["client_id", "client_secret", "user_agent"]
    optional_fields: ["username", "password"]
    test_endpoint: "subreddit_access"
    rate_limits:
      requests_per_minute: 60
  
  alpha_vantage:
    description: "Alpha Vantage API for additional financial data"
    required_fields: ["api_key"]
    optional_fields: []
    test_endpoint: "quote_data"
    rate_limits:
      requests_per_minute: 5
  
  news_api:
    description: "News API for additional news sources"
    required_fields: ["api_key"]
    optional_fields: []
    test_endpoint: "headlines"
    rate_limits:
      requests_per_day: 1000

# Logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"